name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Which branch to deploy to peggyjs.org
        required: true
        options:
          - stable

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Enable pnpm
        run: "corepack enable"
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install dependencies
        working-directory: docs
        run: "pnpm i --frozen-lockfile"
      - name: Build
        working-directory: docs
        run: "npm run build"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: docs
